### ISSUE TITLE
Sending SMT queries while evaluate functions (with concrete values)

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#1060]
I did some profiling on sum-to-n. I generate the log through the following process:
```
1. stack build --ghc-options "-eventlog -debug" --copy-bins
2.kprove --haskell-backend-command "/home/zy/workspace/kore/.build/kore/bin/kore-exec --log stdout --log-level debug --log-scope send,recv,translateUninterpreted " ~/workspace/sum-to-n-spec.k -d ~/workspace/evm-semantics/.build/defn/haskell/ --def-module VERIFICATION --depth 1 > log.txt 2>&1
``` 
In the attached [log.txt](https://github.com/kframework/kore/files/3687569/log.txt) line `14555`, there is a SMT query (that I don't know the meaning). The query is generated in the context of evaluating `#asmOpcodes`. However, in the spec, the arguments of `#asmOpcodes` are concrete.
The spec I used is the same as the one in https://github.com/kframework/kore/issues/1002

**Comment by virgil-serbanuta** [comment]
This seems to be enclosed by
```
evaluate-Lbl'Hash'asmOpCodes'LParUndsRParUnds'EVM-ASSEMBLY'Unds'ByteArray'Unds'OpCodes-1-apply
```
starting at line 2071 and ending at line 14604.

I guess that the smt query is sent while evaluating or simplifying the above symbol, by one of these:
https://github.com/kframework/kore/blob/master/kore/src/Kore/Step/Axiom/Evaluate.hs#L100
https://github.com/kframework/kore/blob/master/kore/src/Kore/Step/Axiom/Evaluate.hs#L104

`predicate`, which is and-ed to what we send to the SMT solver, contains the top-level predicate and the predicate we get from evaluating the children.

**Comment by virgil-serbanuta** [comment]
Here's my attempt to make sense of this:

1. `simplifyPredicatesWithSmt` always adds the top+children predicate and checks stuff. I think that we could skip that if (there is at most one non-top children predicate) _and_ (the current predicate is top). This is not hard to do, but also, not trivial.

2. I'm trying to understand the SMT assertion. Somehow it does not make full sense to me. It looks like this:
`assert (and (and (not <1>) stuff) (not (not <1>)))`, where, if I understand the log correctly, `<1>` looks like this:
```
    \equals{SortSet{}, _PREDICATE{}}(
        VarJUMPDESTS:SortSet{},
        /* builtin: */
        Lbl'Unds'Set'Unds'{}(
            /* concrete element: */ LblSetItem{}(
                inj{SortInt{}, SortKItem{}}(/* builtin: */ \dv{SortInt{}}("3"))
            ),
            /* concrete element: */ LblSetItem{}(
                inj{SortInt{}, SortKItem{}}(/* builtin: */ \dv{SortInt{}}("20"))
            )
        )
    ) []
```
Now, `<1>` looks like a substitution, and we usually see negated substitutions in remainders and `owise` clauses. However, this time, it seems that we have a doubly negated substitution. My guess is that we have a function with an `owise` clause which generates the simple negation, while the second negation is added by the remainder (since the owise clause is treated as any other function definition clause, so it can have remainders).

However, we should have detected fairly quickly that we have `x and (not x)`, which means that we combined the two just for this evaluation. One of the two can come from the top-level predicate, but the other must come from the children predicate or the current predicate (of course, both can come from different children).

So, I guess that evaluating `asmOpcodes`, or its children, uses non-symbolic input (i.e. although the thing between the `asmOpcodes`' parenthesis is not symbolic, the function also uses, say, the `jumpDests` cell as input, directly or indirectly).

The above contains a lot of guesses, does it make some sense?

**Comment by yzhang90** [comment]
yes. your explanation makes sense. 
1. `#asmOpcodes` does have `owise` rules.
2. we have `JUMPDESTS ==K #computeValidJumpDests(sumToN)` in the top level constraint and 
```    syntax ByteArray ::= "sumToN" [function]
 // ----------------------------------------
    rule sumToN
      => #asmOpCodes(PUSH(1, 0) ; SWAP(1)                   // s = 0 ; n = N
                    ; JUMPDEST                              // label:loop
                    ; DUP(1) ; ISZERO ; PUSH(1, 20) ; JUMPI // if n == 0, jump to end
                    ; DUP(1) ; SWAP(2) ; ADD                // s = s + n
                    ; SWAP(1) ; PUSH(1, 1) ; SWAP(1) ; SUB  // n = n - 1
                    ; PUSH(1, 3) ; JUMP                     // jump to loop
                    ; JUMPDEST                              // label:end
                    ; .OpCodes
                    ) [macro]
```
