### ISSUE TITLE
Unclear section un definedness in documentation

### ISSUE THREAD

**Issue by MrChico** [kframework/kore#108]
I don't know if this is a "user problem", but this section is pretty hard for me to understand:
<img width="746" alt="screen shot 2018-05-23 at 16 44 31" src="https://user-images.githubusercontent.com/8930559/40431896-aa434766-5ea8-11e8-92ad-0998fe15ff58.png">
Am I supposed to just infer how ρ extends for these symbols? Why are there two sorts at play here? Also, later in the section about equality, it's not clear to me what it means for two patterns to be compared in a context.

**Comment by virgil-serbanuta** [comment]
Here's my take on it, maybe @hreada will add some of these to the document, if they are not already there:

1. Why two sorts: Because the definedness symbol produces predicates, i.e. things that are either "true" or "false" (assuming that, for a given sort s, you identify the empty set with false and the entire Ms set with true), and it is useful to combine predicates that work with different sorts inside (i.e. one would like to write and(a=b, c=d) where a and c have different sorts). The way to solve this is to allow predicates to produce a "true" of any sort.

2. Given the "definedness pattern" axiom, rho extends uniquely to these symbols (the part starting with "it's easy to show that"), so you don't have to infer the extension, you may have just have to prove that the extension is what is given in the documentation.

**Comment by ehildenb** [comment]
Here is an example of why you would want two sorts:

The following program (of sort `Stmt`, with logical variable `V0`) has a potetential division by zero error:

```
(ints x , y ;
x = V0:Int;
y = 200000000;
while(x <= 10) {
    y = y / x;
    x = x + 1;
}):Stmt
```

We would like to restrict to cases where division by zero is not possible

```
(ints x , y ;
x = V0:Int;
y = 200000000;
while(x <= 10) {
    y = y / x;
    x = x + 1;
}):Stmt

/\

(V0 > 0):Bool
```

But Matching Logic operator `/\` has to have the same sort on both sides, because it corresponds to set intersection.

So we do `|V0 > 0 == true|_{Bool}^{Stmt}`, which if `V0 > 0 == true` is Matching Logic true, gets turned into the entire underlying set of sort `Stmt`, and if `V0 > 0 == true` is Matching Logic false, gets turned into the empty set.

In the case of `V0 > 0 == true`, we wouldn't have a division by zero error, and the program is left alone. In the case of `V0 > 0 == true` being false, we are intersection with the empty set and there is no program.

Hope this was coherent.

**Comment by MrChico** [comment]
Yeah, after Grigores presentation on matching logic the other day, this makes a whole lot more sense. Regarding definedness though, iirc the crucial part necessary to show that \overline\rho(\varphi) is either true or false was the axiom that \overline\rho(x) holds for all variables
