### ISSUE TITLE
Simplifiable cycle in a substitution

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#1151]
We met the following situation in the KWASM semantics:
```
config <k> .K </k>
          <a> .Map </k>
syntax Index := Int | Id
syntax Int ::= #compute(Index)
rule #compute(X:Int) => ...
rule #compute(X:Id) => ...

rule <k>  f(TFID:Index) => ... </k>
        <a> #compute(TFID) |-> V </a>
```
f is a constructor. 
Now the current config is `<k> f(X:Int) </k> <a> X |-> VAL </a>`.
The unification will produce the following constraint:
```
TFID = inj{X} /\ X = #compute(TFID)
```
The haskell backend will get stuck while there is clearly a solution here. We need to find a general way to solve it.

**Comment by yzhang90** [comment]
One possible solution is that:
1. We first divide the substitution into two groups: non-simplifiable head and simplifiable head. If there is cycle in the non-simplifiable group, we  just return `unsat`. If all substitutions are in simplifiable group, we just throw error. In the above example, non-simplifable group is `TFID = inj{X}` and simplifiable group is `X = #compute(TFID)`
2. We apply the substitutions in non-simplifiable group to simplifiable group and start to evaluate functions in the simplifiable group. In the above example, we will evaluate `#compute(inj{X})` and get the result `X` and then we got `X = X`, which is trivilly true.
If after step 2, some substitution from simplifiable group moves to non-simplifiable group, we repeat 2 again.
If non-simplifiable group doesn't change and we still have substitution in the simplifiable-group, we will throw an error.

**Comment by virgil-serbanuta** [comment]
1 - Why do we return unsat for non-simplifiable stuff? I understand why we would do that for, say, constructors and inj (unless we can have two sorts `S1` and `S2` with injections both from `S1` to `S2` and from `S2` to `S1`, and, if we assume that this does not happen, we should actually check that's true during verification), but not for unsimplifiable stuff in general. If we have `x=f(x)` where `f` is a function symbol that we don't know how to simplify, that does not mean that `x=f(x)` is unsat. 

2 - I think this is a nice idea, and it would work. If we need more, we could generalize it and evaluate symbols even if that generates splits (but probably we should not evaluate if it leaves remainders). Nitpick: After step 2 we should retry step 1, not 2, since we want to detect if the substitution has just became unsat.

**Comment by yzhang90** [comment]
1 - @virgil-serbanuta I thought non-simplifiable symbol means the constructor and inj, because they can not be further implemented. if `f` is a function symbol, it will be put into the simplifiable group. (My understanding of the term `non-simplfiable symbol may be wrong. You get the idea)

2- You are correct, I'll update the text

**Comment by ttuegel** [comment]
Sorry, I think I introduced the "non-simplifiable" terminology in my discussion with @yzhang90 yesterday. In the substitution simplifier, we already use this terminology to refer to constructors and sort injections: we have axioms for these symbols that say they cannot be simplified.
