### ISSUE TITLE
Outdated Unparse instances for rules

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1196]
For example, the instance for [RewriteRule](https://github.com/kframework/kore/blob/master/kore/src/Kore/Step/Rule.hs#L238) is missing several fields.

**Comment by virgil-serbanuta** [comment]
I propose to match function the arguments with `Constructor _ _ _ ... ` form more often in order to make sure that we don't forget updating the function when a struct changes. I.e. we should ask ourselves if we expect to change that function if we add a new field to the struct, and, if we do, we should match as mentioned above.

**Comment by ttuegel** [comment]
I agree, in fact that's what I did in my draft branch.
