### ISSUE TITLE
Missing unification cases no longer produce errors

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1256]
At one time, it was an error if a particular unification case was not recognized when applying rules. Now it seems that we promote unknown cases to equalities in a (likely) futile attempt to continue.

See also: #1255

**Comment by virgil-serbanuta** [comment]
Technically speaking, we still produce errors when we don't know how to unify things. However, we have a fallback case for unifying functional stuff, so, in practice, we think we know how to all things that we actually see in our input files.

Producing an error for this case does not work out of the box, since we have rules that (roughly) work like this:
```if true then A else B => A```
which we may try to apply to
```if (X <Int Y) then something else somethingelse```
and this will crash at unification time, because we don't know how to handle `true` vs `X <Int Y`.
To see an example of this, for now you can run the `src/main/k/working/smc` test with this PR: https://github.com/kframework/kore/pull/1302 , though the PR may change or disappear in the future.

Possible solutions:
1. Maybe it's not that bad to get an error after unification, saying that the axiom does not cover all the variables - searching the predicate for an `equals` containing the said variable is almost equivalent to getting an error about an unknown unification case. We could even have some heuristics in our error code doing that for the user.
2. Whitelist various cases in which it's ok to return equalities, e.g. when the term coming from the rule is a concrete one. This does not solve all issues (e.g. `C(X)` in the rule vs `Y` in the term would still be accepted, though that might be solvable). Also, it's not a big issue, but whoever does this should also pay attention to argument order swapping in the unifier, e.g. here: https://github.com/kframework/kore/blob/master/kore/src/Kore/Builtin/AssociativeCommutative.hs#L820 . Or we could blacklist stuff, of course.
3. Make the semantics to not use, say, domain values in rules. Instead, we should use variables, and we should use the domain value in the `requires` clause. That could be done automatically when compiling the `k` rules to `kore`.

I like 1 the most, then 3 if we do it at compilation time, then 2, then 3 if we do it manually. All of them should work, and all have some unknown elements that could surprise us (though 1 can't really go wrong, it can only be less useful than people hope).

**Comment by virgil-serbanuta** [comment]
@ttuegel I'll unassign this bug since it's Thanksgiving, which means that I can't ask the people for which this was annoying to see if item 1 would be good enough for them.

**Comment by ttuegel** [comment]
> We could even have some heuristics in our error code doing that for the user.

We could probably identify subterms of the conditions involving the missing variables.

Another option, which I mentioned in the daily meeting, would be to allow `function = non-simplifiable` equalities to be created during unification. This would allow `f(x) = 1` for example, but forbids `f(x) = f(y)`, which is not usually what we want (and is in fact the case causing problems for us now).
