### ISSUE TITLE
Resume in-progress proofs

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1277]
The output of `kprove` should not be a single pattern, but rather an update spec module where

- Each claim that was proved appears with the `trusted` attribute.
- For each claim in progress,
  - For each unproven configuration, there is one claim from that configuration to the claim target.
  - There is one `trusted` claim from the original source of the claim to the disjunction of all unproven configurations.
- Each claim which has not been started appears unchanged.

The user can modify the updated spec module and resume the proof by pointing `kprove` at the new spec module. The user will mainly add new lemmas to remove infeasible branches, which is usually safe. Of course, this also allows the user to do unsound things, so the updated spec shall come with a prominent warning that they must eventually run the proof from the beginning with any modifications.

**Comment by ttuegel** [comment]
Clarification from @yzhang90:

We do not need to output any un-`trusted` claims into the updated spec module. We should output only the `trusted` claims to recover the current proof state. The current proof state should be represented as a Kore module of trusted claims and applied by the backend _once_ at start-up. We do not want to apply the trusted claims as circularity rules.

**Comment by yzhang90** [comment]
what you described looks good to me. One thing that I'm not sure is that whether we should trust the frontend or not. Tom thinks that the frontend may not be consistent between runs. As a result, we need to convert the generated module back to K and use the frontend to compile the whole thing again.

**Comment by ttuegel** [comment]
> As a result, we need to convert the generated module back to K and use the frontend to compile the whole thing again.

As I said, I don't think we should actually do that, I think we should just invalidate the trusted claims file whenever the definition changes.

**Comment by yzhang90** [comment]
If users only add some lemmas, would that be considered as definition changes? Note that all the semantic rules and lemmas will be combined into a single vdefinition.kore file.

**Comment by ehildenb** [comment]
If we are going with adding `trusted` claims to the spec, then I think it needs to be done by the frontend (because there is no reason for this to be backend specific).

If we use a structured proof log, the trusted claims can remain as Kore and be backend specific, which means we're not limited to interactions that the frontend supports.

**Comment by ehildenb** [comment]
Discussed with @ttuegel IRL, and it sounds like a good approach (different than what I expected). Here is a summary of my understanding:

-   Haskell backend has extra option `--save-proofs` or something.
-   If that option is turned on, all proofs are saved in a `trusted-claims.kore` file which the frontend never sees.
-   If `--save-proofs` is turned on in a subsequent run, then once at startup for each proof goal, the Haskell backend will check if any of the rules in `trusted-claims.kore` can be applied. If so, it will apply them immediately, then resume the normal proof process.
-   No cache invalidation will take place, it's up to the user to decide if they need to invalidate by deleting the `trusted-claims.kore` file. This is because of 2 reasons, (1) deciding algorithmically when the `trusted-claims.kore` file is invalid is "really hard", with lots of corner cases, and (2) when the user is satisfied with their proof, they should delete this file and re-run anyway (so the point is to speed up producing the proof, not to assist in the final execution of it).

**Comment by ehildenb** [comment]
I also agree with not using `trusted-claims.kore` as circularities, because that will be way too expensive.

**Comment by yzhang90** [comment]
I'm also on the same page.
