### ISSUE TITLE
Create a Substitute class

### ISSUE THREAD

**Issue by traiansf** [kframework/kore#1383]
Implement a `Substitute` class that has `freeVariables`, `refreshVariables`, `mapVariables`, and `traverseVariables` (which basically support capture-avoiding substitution), and also `substitute`?

**Comment by ttuegel** [comment]
We did not add `freeVariables` to the class `Substitute` because it was convenient to define `freeVariables` for types that don't have a natural `Substitute` instance. We did not add `refreshVariables` to the class because it already belongs to a class for rules, and not all patterns have a sensible notion of refreshing variable names. We also did not add `mapVariables` and `traverseVariables` because these functions need to change the type of variable names.
