### ISSUE TITLE
Unification of injected overloaded constructors

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1414]
There is a missing unification case for two injected, overloaded constructors:

```
\inj{Sub1, Super}(Overloaded1) ∧ \inj{Sub2, Super}(Overloaded2)
```

where there is an overloading symbol `Overloading` in a sort `Mid <= Super`.
We do not know how to handle this case.

See also: #1269

**Comment by traiansf** [comment]
I've discussed this briefly with @virgil-serbanuta and we think this should work:

* If Sub1 and Sub2 have no common  subsorts, this fails, being already handled by `unificationInj`
* Otherwise, look for an Overloaded' which overloads both Overloaded1 and Overloaded2 (and, therefore, is on a common supersort Super', subsort of `Super`)
  - If found, then transform `\inj{Sub1, Super}(Overloaded1(child1)) ∧ \inj{Sub2, Super}(Overloaded2(child2))` into `\inj{Sub1, Super}(Overloaded1(child1)) ∧ \inj{Sub2, Super}(Overloaded2(child2))` \inj{Sub1,Super'}(Overloaded'(\inj{SC1,SC1'}(child1) ∧ inj{SC2, SC2'}(child2)`
- if not found, unification is not possible, return `\bottom`.

**Comment by ttuegel** [comment]
Some discussion items from the daily meeting, and unresolved questions:

1. We need to attempt resolving overloading when unifying injections for `wasm-semantics`.
1. When the children are overloaded into a common sort that is a subsort of `Super`, we can lift the children into the overloading sort and continue unification there.
   - What if there are multiple suitable overloading symbols?
   - It might be helpful to make an `OverloadGraph` similar to `SortGraph`.
   - It seems like overloads and injections are intertwined; it would be a good idea to think about how (or if) we will separate these responsibilities.
1. When the children are overloaded into a sort that is a supersort of `Super`, we should throw an error. We do not understand how this could occur in a correct definition or how to handle it safely.
