### ISSUE TITLE
Confusing Map unification error message

### ISSUE THREAD

**Issue by daejunpark** [kframework/kore#1504]
To reproduce:
```
$ git clone git@github.com:runtimeverification/beacon-chain-verification.git
$ cd dynamic
$ kompile --backend haskell dynamic-abstract-beacon-chain.k
$ krun --depth 51 test1.abc
```

For more details:

At step 50, we have:
```
$ krun --depth 50 test1.abc
<T>
  <k>
    activateValidators ( .List ) ~> processSlots ( 4 )
  </k>
...
```
But the next step failed.
```
$ krun --depth 51 test1.abc
kore-exec: [2020-02-03 18:58:13.377194551] Error (ErrorException): Unification case that should be handled somewhere else:
attempting normalized unification with a 
non-element-variable opaque term or 
non-function maps could lead to infinite loops.
...
```
where the `activateValidators` rule is simply:
```
rule activateValidators(.List) => .
```

I'm using the LIST.size hook version (https://github.com/kframework/kore/commit/c5f3056cb81548798051c3dc107e054e40ad939d).

**Comment by daejunpark** [comment]
@ttuegel said:
> Thomas Tuegel  7:44 PM
There is a Map in the configuration, right? I guess that when the activateValidators rule is elaborated in Kore, the cell containing a Map gets completed with something that doesn't get normalized properly...

**Comment by ttuegel** [comment]
The resolution was:

> The error is related to attempting this rule: https://github.com/runtimeverification/beacon-chain-verification/blob/master/dynamic/dynamic-abstract-beacon-chain.k#L460-L465
I realize that this rule should not apply, but we have show it doesn't unify.
The problem with this rule is that it has a function on the left-hand side. That looks strange to me; should it say Validators => Validators[ V.id <- ... ] instead?

@daejunpark asked:

>so it tried to unify the non-k cells even if the k cell is not matched?  btw, do you have some mechanism to find candidate rules before matching/unification?  also, how did you find this issue?  i mean, how should i debug this similar issue later by myself?

to which I answered,

> There are no "cells" in the backend, so yes, the backend tried to unify the entire configuration.
> There is a mechanism to find candidates for matching equality (function) rules, but the backend must always attempt every semantic rule.
> I found this issue by examining the Kore patterns in the error message. One of the patterns was an un-evaluated function (MAP.update). I looked for rules involving that function in the definition.kore file and found a rule with it on the left-hand side. That was suspicious, so I went to the corresponding rule in the .k file.

**Comment by ttuegel** [comment]
We should think about how to improve this error message, or how to avoid it if possible. The error was pretty simple to diagnose, so a clearer message would help verification engineers debug the problem themselves.

**Comment by daejunpark** [comment]
please feel free to close this issue.

**Comment by ttuegel** [comment]
We can avoid this error message by recognizing sooner when unification yields `\bottom`. For this case in particular, and probably most cases, the most important unification sub-problem is unifying constructor-like symbols. This sub-problem type is solved by unifying the pairs of arguments of the two (identical) symbols: we unify all pairs of arguments, then conjoin their unification solutions, so that if any one is `\bottom`, then the solution is `\bottom`. This procedure involves computing the unification of _all_ pairs of arguments, even though the result is `\bottom` if any one unification yields `\bottom`. So, we can avoid encountering this error condition if we short-circuit while unifying constructor arguments; because we process arguments from left to right, and the `<k>` cell appears on the left, we won't continue unifying if the `<k>` cell doesn't unify.

We can implement the short-circuiting behavior with a simple monad transformer,

```.hs
newtype BottomT m a = BottomT { unBottomT :: MaybeT m a }
    deriving (Functor, Applicative, Monad, MonadTrans)
```

Each constructor argument unification solution will be short-circuited if `\bottom`. Besides implementing the `newtype`, the only changes are: check each argument pair's unification result for `\bottom` and un-wrap the `newtype` after unifying all the arguments. This should be a very small change.

**Comment by ttuegel** [comment]
On second thought, this short-circuiting should already be applied.
