### ISSUE TITLE
KEVM: HKG token specs

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1508]
These are the times on the Java backend of the relevant specs, which we offer as a proxy for complexity:

```
55.28s  tests/specs/erc20/hkg/totalSupply-spec.k
57.12s  tests/specs/erc20/hkg/allowance-spec.k
60.04s  tests/specs/erc20/hkg/transfer-success-2-spec.k
60.70s  tests/specs/erc20/hkg/balanceOf-spec.k
62.32s  tests/specs/erc20/hkg/transfer-success-1-spec.k
62.85s  tests/specs/erc20/hkg/transfer-failure-1-spec.k
64.02s  tests/specs/erc20/hkg/transfer-failure-2-spec.k
64.17s  tests/specs/erc20/hkg/transferFrom-failure-2-spec.k
67.48s  tests/specs/erc20/hkg/approve-spec.k
67.91s  tests/specs/erc20/hkg/transferFrom-success-1-spec.k
68.01s  tests/specs/erc20/hkg/transferFrom-success-2-spec.k
148.64s tests/specs/erc20/hkg/transferFrom-failure-1-spec.k
```

**Comment by ttuegel** [comment]
I reset the appetite to "small" just now. After the lemmas are done, I think we should try all the specs and open new issues for the different problems. Each new issue can get its own appetite. That way, we get a better picture of the total amount of work needed.

**Comment by virgil-serbanuta** [comment]
Issue 1: Lemmas that use reflection.
https://github.com/kframework/evm-semantics/blob/master/tests/specs/erc20/abstract-semantics-segmented-gas.k#L20
https://github.com/kframework/evm-semantics/blob/master/tests/specs/erc20/abstract-semantics-segmented-gas.k#L35
https://github.com/kframework/evm-semantics/blob/master/tests/specs/erc20/verification.k#L14

**Comment by virgil-serbanuta** [comment]
Issue 2: Failed substitution coverage check (rewrite lemmas with functions in the lhs):
https://github.com/kframework/evm-semantics/blob/master/tests/specs/erc20/abstract-semantics-segmented-gas.k#L26

**Comment by yzhang90** [comment]
Regarding the issue2, i think when applying the lemma, we should always try matching first, even though the function in the LHS is not injective.

**Comment by ttuegel** [comment]
> i think when applying the lemma, we should always try matching first

I don't think that's sound. Every matching solution is a unification solution, but it may not be the unique unification solution. So, we have to consider the negation of the matching solution, and then I think we are back where we started.

**Comment by yzhang90** [comment]
There are several points:
For all path proof:
1. (semantics) lemmas are the facts or summaries about the transition system. If a lemma is failed to be applied, I may fail to prove the spec.  However, i can not prove something wrong (it is different from missing to apply a transition rule).
2. All the free variables in the lemmas are universally quantified. if i can find a matching solution, there are 2 possibilities:
1) the matching solution (and the side condition) entirely covers the current config, then for each instantiation of the current config, I can use the matching solution to instantiate the lemma.
2) the matching solution (and the side condition) partially covers (or can not cover at all) the current config, then the part (negation of the matching solution) will fail to apply the spec. There can be other unification result which will cover the current config and we simply miss that opportunity. However, according to point 1, failing to apply a lemma is still sound.

**Comment by ttuegel** [comment]
If it is sound to use matching to apply lemmas, could you @yzhang90 and @traiansf please update the design document describing the all-path proof strategy? And then we will implement the changes.

Is it sound to do the same for one-path claims?

**Comment by yzhang90** [comment]
> Is it sound to do the same for one-path claims?
I think so. Currently, the haskell backend can not unify non-injective function terms, so the backend either fail to apply the claim or get stuck. If we switch to this matching approach, at least we can move forward. 

If later we can return multiple unification solutions, we need to connect the solutions with `or` and try them all.

**Comment by virgil-serbanuta** [comment]
I think that this is a bit confusing.

When I write `phi => psi` in k, that can mean a lot of things in ML:

1. It can mean `phi = psi` (I think that happens if the symbol at the top of `phi` is a function).
2. It can mean `phi rewritesTo psi` if we are doing concrete execution and, I guess, the symbol at the top of `phi` is a constructor.
3. It can mean that `phi` and `psi` are part of a complex axiom that merges all the axioms that we currently call "rewrite axioms" and specifies how to take a single all-path step. Unfortunately, this axiom is not present explicitly in the `kore` file, and we use all the available rewrite rules to simulate it.

However, if we have a `phi => psi` rewrite lemma in an all-path context, what does it mean?
1. If it is similar to item 3 above and it should get merged in the same axiom (I think this is what the Haskell backend does right now), then I think we should not use matching, see the example below.
2. If it can be used as a replacement for that axiom, then I still think we should not use matching, see the same example.
3. Something else?

Example:

Let's say that we have a function `ct` from `Bool` to `Bool` defined by `ct(x) = true`.
Let's say that we also have the following rewrite lemma `<k>ct(x)</k> => <k>x</k>` and we want to apply it to `<k>ct(true)</k>`.

If we use matching, then the result is `<k>true</k>`. If we use unification, then the result is `<k>false</k> or <k>true</k>`. I think that, for all-path, the latter is the right result, because, if we remove the `<k>false</k>` branch we will not analyse all possible paths.

**Comment by virgil-serbanuta** [comment]
@traiansf explained to me why my example does not work if a rewrite lemma is an all-path claim: the result is not `<k>false</k> or <k>true</k>`. He also explained that using matching if we don't have a remainder works because the claim is true for any possible representation of `phi`, regardless of how we get it (matching, unification, or random number generators).

**Comment by ttuegel** [comment]
Closing in favor of #2113.
