### ISSUE TITLE
When a branch evaluates to `Reached bottom` it is not reported in kprove output

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#1614]
In the final pretty-printed output we see just the result of the branch that continued evaluation. So the only way we can find the branching is by REPL.

This is related to #1604 

If execution of a branch reaches `bottom` that means the branch is infeasible and branching should not have happened in the first place.

**Comment by ttuegel** [comment]
`Reached bottom` means that the proof succeeded on the current branch, i.e. if the previous configuration was `This` and the proof goal is `Goal`, then `This → Goal` holds. The backend checks this implication by checking the (un)satisfiability of `¬(This → Goal) = This ∧ ¬ Goal`. It is possible that this pattern is unsatisfiable because `This = \bottom`, but usually it's just that the implication was proved on a branch. The backend doesn't really distinguish the two conditions, though, and we could do a better job of reporting that. `kprove` doesn't really allow us to return multiple patterns through the frontend, but would it be sufficient to report a warning when the current configuration itself reached `\bottom`? As you pointed out, that shouldn't happen.

For detecting and eliminating unwanted branching, you can send the `--breadth N` option to `kore-exec`, and the backend will halt if the number of concurrent branches exceeds `N`.

**Comment by denis-bogdanas** [comment]
Thanks for explanation. I had different assumptions from Java backend. There every branch represents a feasible path. In the case of Symbolic testing ERC20 we are working on, branch with "bottom" was infeasible. It would be good to automatically ignore such branches, that would allow continuing the execution smoothly in REPL.
