### ISSUE TITLE
kore-exec and kore-repl report non-determinism inconsistently

### ISSUE THREAD

**Issue by daejunpark** [kframework/kore#1615]
It seems that non-constraint predicates (i.e., predicates that appear outside the `requires` clauses) are incorrectly propagated to the top-level.

Consider the following definition:
```
$ cat e.k
module E

imports BOOL
imports INT

syntax Cmd ::= "run"

syntax Cmd ::= case(Bool, Bool)

rule run => case(?X =/=Int 0, ?X ==Int 0)

endmodule
```

The result of `run` is:
```
$ cat 1.e
run
$ krun 1.e
  <k>
    case ( false , true )
  </k>
#And
  {
    ?X
  #Equals
    0
  }
```
while it should preserve the two predicates `?X =/=Int 0` and `?X ==Int 0` as they are.

~This issue allows kprove to prove a false statement, making kprove unsound.~

**Comment by daejunpark** [comment]
Hmm, but `krun --search` seems to correctly explore both cases.
```
$ krun --search 1.e
    #Not ( {
      ?X
    #Equals
      0
    } )
  #And
    {
      Result
    #Equals
      <k>
        case ( false , true )
      </k>
    }
#Or
  {
    Result
  #Equals
    <k>
      case ( true , false )
    </k>
  }
```

**Comment by daejunpark** [comment]
More interestingly, `kprove` doesn't agree with the REPL mode output.

For example, consider the following definition:
```
$ cat a.k
module A

imports BOOL
imports INT 

configuration <T> <k> $PGM:Cmd </k> <c> 0 </c> <d> true </d> </T>

syntax Cmd ::= case(Bool, Bool)

rule case(C, _) => . requires C
rule case(_, C) => . requires C

syntax Cmd ::= "foo"

rule <k> foo => . </k>
     <c> X:Int </c>
     <d> _ => true </d>
     requires X =/=Int 0

rule <k> foo => . </k>
     <c> X:Int </c>
     <d> _ => false </d>
     requires X ==Int 0

endmodule
```

Consider the following spec that is not satisfied by the above definition:
```
$ cat a-spec.k
module A-SPEC

imports A

rule <k> case(X =/=Int 0, X ==Int 0) ~> foo => . </k>
     <c> X:Int </c>
     <d> _ => false </d>

endmodule
```

Now `kprove` fails to prove it, which is correct:
```
$ kprove a-spec.k 
  #Not ( {
    X
  #Equals
    0
  } )
#And
  <T>
    <k>
      .
    </k>
    <c>
      X
    </c>
    <d>
      true
    </d>
  </T>
```

But, the REPL mode output does not agree:
```
$ kprove --haskell-backend-command "kore-repl --repl-script kast.kscript " a-spec.k 
Welcome to the Kore Repl! Use 'help' to get started.

Kore (0)> step
Kore (1)> leafs
UnevaluatedNode: [1]
Kore (1)> step
Kore (2)> leafs
UnevaluatedNode: [2]
Kore (2)> step
Stopped after 0 step(s) due to reaching end of proof on current branch.
Kore (2)> leafs
No leafs found, proof is complete.
```
The `No leafs found, proof is complete.` message means that it proves the spec, right?

See also the execution trace:
```
Kore (2)> konfig-n 0
Config at node 0 is:
<T>
  <k>
    case ( false , true ) ~> foo
  </k>
  <c>
    0
  </c>
  <d>
    _0
  </d>
</T>
Kore (2)> konfig-n 1
Config at node 1 is:
<T>
  <k>
    foo
  </k>
  <c>
    0
  </c>
  <d>
    _0
  </d>
</T>
Kore (2)> konfig-n 2
Config at node 2 is:
<T>
  <k>
    .
  </k>
  <c>
    0
  </c>
  <d>
    false
  </d>
</T>
Kore (2)> konfig-n 3
Config at node 3 is:
Reached bottom
```

But, confusingly, when the REPL exits, it emits something.
```
Kore (2)> exit
    #Not ( {
      X
    #Equals
      0
    } )
  #And
    <T>
      <k>
        case ( true , false ) ~> foo
      </k>
      <c>
        X
      </c>
      <d>
        _0
      </d>
    </T>
#Implies
  ( #wEF ( <T>
    <k>
      .
    </k>
    <c>
      X
    </c>
    <d>
      false
    </d>
  </T> ) )
```
What does this mean?  Especially, what does `#wEF` mean?  How should I interpret the REPL output that doesn't seem to agree with the non-REPL kprove output?  What am I missing here?

**Comment by ttuegel** [comment]
I changed the title to reflect the symptom. In fact, `==Int` is a term, not a predicate, so the problem is something else.

`krun` without `--search` intentionally only explores the first execution path it finds. That is useful for concrete execution because it is faster, but we should document this behavior.

The `#wEF` in `kore-repl`'s output is the key to the mystery: it is the weak-exists-finally modality for _one-path_ claims. Because the definition is non-deterministic (I assume) you intended to write _all-path_ claims, in which case this should be `#wAF`.

We need to check:

- [ ] The default claim type in the frontend (should be all-path).
- [ ] `kore-repl` should handle all-path claims, but it evidently re-interprets them as one-path claims.

**Comment by daejunpark** [comment]
I confirm that I intended all-path claims.  I thought that they are all-path by default.

**Comment by ana-pantilie** [comment]
@ttuegel @daejunpark It looks like the default claim type is still one-path, so both `kore-exec` and `kore-repl` are running the same one-path claim. 

The reason the outputs of `kore-exec` and `kore-repl` are different in the scenario above is that during start-up simplification the `repl` splits the claim into two claims, and from what I can see you only started proving one of them. You can check the status of all claim proofs using the `repl` command `proof-status`. I tried to prove the second claim as well, and it ended up in a stuck node with the expected final configuration. Also, when the `repl` exits, it takes will print new claims created from each remaining configuration, so that's why the `#implies #wEF ...` appears.
