### ISSUE TITLE
Node stuck in the state `UnevaluatedNode` when it evaluates to `Bottom` in one step

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#1637]
How to reproduce:
test.k:
```
requires "domains.k"

module TEST
    imports DOMAINS

    configuration
      <k> $PGM:KItem </k>

    syntax KItem ::= "#assume" Bool
    rule <k> #assume B => . ...</k>
      ensures B

endmodule
```
test-spec.k:
```
requires "test.k"

module TEST-SPEC
  imports TEST

  rule <k> #assume false => . </k>

endmodule
```

Result in REPL:
```
Kore (0)> leafs
UnevaluatedNode: [0]
Kore (0)> step
Stopped after 0 step(s) due to reaching end of proof on current branch.
Kore (0)> leafs
UnevaluatedNode: [0]
Kore (0)> konfig
Config at node 0 is:
<k>
  #assume false
</k>
```

**Comment by traiansf** [comment]
not sure what the issue is here, but I'd like to point out that the rule:
```
rule <k> #assume B => . ...</k>
      ensures B
```
is problematic, as it will make the specification inconsistent (in ML)
In general all rules with ensures (except for those introducing an existential variable) tend to fall in this trap.

Proof

Lets push the rewrite to the top
`<k> #assume B ~ K</k>   =>   <k> #assume B ~ K</k> ensure B`
And transform it into ML
`<k> #assume B ~> K</k>   ->\next( <k> #assume B ~> K</k> /\ B=true)`
This is an axiom, therefore it is valid.

Now, if we instantiate `B` with `false` we get that the following is also valid:
`<k> #assume false ~> K</k>   ->\next( <k> #assume B ~> K</k> /\ false=true)`

But, as you pointed out,  `false=true` is `\bottom`, hence the whole `\next( <k> #assume B ~> K</k> /\ false=true)` is bottom, as well.

However, since all in the rhs are constructors, the interpretation of
`<k> #assume false ~> K</k>` will be a singleton, which cannot be a subset of the empty set.

Hence, there can be no model satisfying 
```
  rule <k> #assume B => . ...</k>
      ensures B
```

**Comment by yzhang90** [comment]
@traiansf i agree. Then #assume should not be a language constructor. The only axiom about #assume should be 
```
  rule <k> #assume B => . ...</k>
      ensures B
```

**Comment by traiansf** [comment]
Ok, if `#assume` is declared as an uninterpreted (partial) function, then the above works, with the understanding that `#assume(false)` can be derived as being false with the above reasoning.

**Comment by denis-bogdanas** [comment]
So what is the status of this? Is is a valid bug? Note that `#assume` is not a function but a constructor. In SOLAR project its rule was a trusted rule in extended definition. We can do the same here if it helps.

**Comment by yzhang90** [comment]
@ttuegel @traiansf Can we introduce an attribute to avoid generating constructor axiom for a language constructor?

**Comment by ttuegel** [comment]
> Can we introduce an attribute to avoid generating constructor axiom for a language constructor?

If you don't introduce such constructor axioms, then it's not a constructor, and we can't unify on it during execution the way you would want to. If `#assume` is an uninterpreted symbol, it could plausibly unify with _anything_. We need the constructor axioms to tell us that `#assume` only unifies with itself.

**Comment by ttuegel** [comment]
> However, since all in the rhs are constructors, the interpretation of
> `<k> #assume false ~> K</k>` will be a singleton, which cannot be a subset of the empty set.

@traiansf Could you explain this a different way? It doesn't make sense to me; the rule seems to say `#assume false -> \bottom` or `\not (#assume false)`, which seems fine to me.

**Comment by denis-bogdanas** [comment]
This issue makes `kore-exec` unusable because one execution branch will get stuck on `#assert false`. Only `kore-repl` can be used. Please consider it top priority.

**Comment by ttuegel** [comment]
@traiansf clarified for me that to have an axiom such as:

```
axiom \not (<k> #assume false ~> K </k> ...)
```

We need to modify the constructor axioms:

1. ~Total~
2. ~Functional~ Function-like (We really need better terminology here, I don't care if it is standard.)
2. Injective
3. No-junk
4. No-confusion
