### ISSUE TITLE
Exit code is ignored when final state has side conditions

### ISSUE THREAD

**Issue by nishantjr** [kframework/kore#1872]
```
module TEST
    imports INT

    configuration <k> .K </k>
                  <exitcode exit=""> 23 </exitcode>
    rule <k> .K  => ?_:Int </k>

    syntax KItem ::= "even" | "odd"  
    rule I => even  requires I %Int 2 ==Int 0
    rule I => odd   requires I %Int 2 ==Int 1
endmodule
```

This definition always returns with exit code `111`

**Comment by ttuegel** [comment]
We need to move [`execGetExitCode`](https://github.com/kframework/kore/blob/master/kore/src/Kore/Exec.hs#L255) into [`exec`](https://github.com/kframework/kore/blob/master/kore/src/Kore/Exec.hs#L218) so that we can apply `getExitCode` to the configuration while the side conditions are still held separately. We will have to tweak `execGetExitCode` slightly, so that it only uses the function evaluator instead of calling `exec`.
