### ISSUE TITLE
Breadth limit does not work

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#1903]
The `--breadth` option does not work with search. It probably doesn't work with execution or proving, either. There are at least two deficiencies:

1. With `--breadth 0`, the backend enters a loop and gradually takes up all available memory.
2. With `--breadth 1`, the backend executes normally, with no breadth limit.

See also: #1902

**Comment by ana-pantilie** [comment]
I have two observations:
1. Why are we removing one element from the `Seq` [here](https://github.com/kframework/kore/blob/acc5f4336f4645d1dab92016cc00635504b794ad/kore/src/Kore/Step/Strategy.hs#L555)?
2. It appears that the backend loops when entering the branch above, where the length of the `Seq` - 1 exceeds the breadth limit.

Since this function is used by both `search` and `prove`, the behaviour is the same.
