### ISSUE TITLE
`#Ceil` rule which depends on top constraint not applied

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#1916]
To reproduce: https://github.com/runtimeverification/erc20-verification/pull/75
Stuck part, in top constraint:
```
  #Not ( #Ceil ( #lookup ( ?STORAGE0 , keccak ( #buf ( 32 , ?ACCT ) ++ b"0000000000000000000000000000000000000000000000000000000000000000" ) ) ) )
#And
...
```

Rule that should apply, in `evm-symb-testing.md`
```
    rule #Ceil(#lookup(STORAGE, _))                  => #True
      requires #isValidStorage(STORAGE)                                         [anywhere, simplification]
```
Top constraint that should match rule side condition:
```
#And
  {
    true
  #Equals
    #isValidStorage ( ?STORAGE0 )
  }
```

**Comment by ttuegel** [comment]
The problem is that we use `simplifyConditionalTermToOr` [here](https://github.com/kframework/kore/blob/68c549b01e21356fc82f93fb8b7b62b4470208e2/kore/src/Kore/Strategies/Goal.hs#L982), which simplifies the term but does not fully simplify the resulting conditions. We should use `Kore.Step.Simplification.Pattern.simplify` instead.
