### ISSUE TITLE
When #Ceil failure occurs make this obvious in the configuration

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#1990]
Right now, `#Ceil` failure occurs for a term that has `#Ceil` rule, stuck configuration won't display any `#Ceil` terms, making diagnosis not trivial.
For example, if we have this #Ceil rule in KEVM:
```
rule #Ceil(#buf(SIZE, DATA)) => {(0 <=Int SIZE) andBool #rangeBytes(SIZE, DATA) #Equals true}  [anywhere, simplification]
```
Stuck configuration looks like:
```
  #Not ( {
      true
    #Equals
      0 <=Int ?ACCT0
    }
  #And
    {
      true
    #Equals
      ?ACCT0 <=Int 115792089237316195423570985008687907853269984665640564039457584007913129639935
    } )
#And
  <kevm-specs>
    <kevm>
      <k>
        #assume notBool ?ACCT0 ==Int ?ACCT ~> #loadERC20Bytecode ?ACCT0 ~> 1 ~> #push ~> #setLocalMem 128 32 #buf ( 32 , ?ACCT0 ) ...
      </k>
```

The `#Not` term at the top is the result of `#Ceil(#buf)` application.

Expected: It would be good to add another term to the top of configuration that makes situation obvious, like `#Failure(#Ceil(#buf(...)))`.

Similarly should be displayed failure of Set concatenation, which in fact has a hidden `#Ceil` rule.

**Comment by ttuegel** [comment]
I don't think this will be needed now that #1665 is fixed.

**Comment by denis-bogdanas** [comment]
Not sure what you mean. That there won't be any issues with `#Ceil` to debug? I tend to disagree. This is a debugging improvement that will be needed whenever we will have to debug `#Ceil` rules, which clearly is an important part of proof writing in Haskell backend. This will be very important to reduce entrance barrier for newcomers, but will be useful for everybody.

**Comment by ttuegel** [comment]
Can you give another example? The proof in the original report is "stuck" due to a backend bug. In my opinion, there is nothing for the user to debug there. I don't think it can be fixed by adding lemmas or side conditions, but it should be reported so that we can fix the bug.

**Comment by denis-bogdanas** [comment]
I got the configuration above on recent, properly working Haskell backend. It happened because `#buf` term was created before the range restrictions that would help solve `#Ceil(#buf)`. The solution was to reorder some logic in symbolic tester, to ensure range restrictions are always created before the `#buf` that needs them.

This is a situation that might easily occur in future for other semantics. We need efficient ways to debug it.

**Comment by ttuegel** [comment]
Unless I'm completely misreading it, that configuration has the following form:

```
#Not ( #Ceil ( #buf(...) ) ) #And ... #buf(...) ...
```

That's `#False`, and if the backend reports it as a stuck configuration, that's a bug in the backend.

**Comment by denis-bogdanas** [comment]
Then please explain how this `#Ceil` magic works, preferably in a wiki page. I understand the following:

When a non-functional function term `foo()` is encountered, configuration is split into 2 branches, one with `#Ceil(foo)` another with `notBool #Ceil(foo)`. Rule `#Ceil(foo)` helps evaluating both sides. The first branch has to evaluate to bottom with the help of path condition and lemmas. If it fails to evaluate to Bottom, we'll get stuck terms like above, with no direct clue that it originated from a failing `#Ceil`. Please correct me where I'm wrong.

**Comment by ttuegel** [comment]
This is what happens: Unifying a variable `X` with a term `foo()` introduces a condition `#Ceil( foo() )`. If this happens when unifying the left-hand side of a rule with the configuration, then `#Ceil( foo() )` becomes a requirement to apply the rule. This requirement is where the backend splits the configuration:

1. `#Ceil( foo() )` holds, and the rule applies.
1. `#Not #Ceil( foo() )` holds, and the rule does not apply.

Usually, the `#Not #Ceil( foo() )` case needs to be refuted, or the proof becomes stuck (no rules apply) as in #1665. To fix that issue, we realized that for any term `T`, the formula `T = T #And #Ceil(T)` is valid in Matching Logic. The backend now applies that identity to the left-hand side of the claim when checking the final implication, introducing `#Ceil(left-hand side)` into the side condition at the top level. When `foo()` appears in the left-hand term, the `#Ceil(left-hand side)` will contradict the `#Not #Ceil( foo() )` so that the claim is shown to hold by the principle _ex falso quodlibet_. After fixing #1665, there is practically no reason for a `#Not #Ceil` condition to appear in a stuck configuration, and I would go so far as to say that it is a bug in the backend if such condition appears.

Note about efficiency: we re-evaluate `#Ceil(left-hand side)` every time we check the final implication. The optimization we are undertaking for #1911 is to apply the identity at the start of each proof step, instead of during the final implication check. At each step, we will only need to evaluate the `#Ceil` of any _new_ partial sub-terms of the left-hand side. This means that we will generally evaluate a `#Ceil( #buf(...) )` the first time the `#buf(...)` appears, and then never evaluate the condition again. As a side effect, the `#Not #Ceil` branch of most (maybe all?) rules won't be created in the first place.

**Comment by denis-bogdanas** [comment]
Thanks for detailed explanation. What I digested:
1. If every time `#Not #Ceil(foo())` is introduced, you practically add `#And #Ceil(foo())` to it, which turns everything to `Bottom`. Then what's the point of creating `#Not #Ceil(foo())` branch in the first place?
2. `#Ceil(foo())` is added only when `foo()` is unified with a variable, e.g. when a variable from a rule matches `X`. Not at the moment `foo()` is added, unconditionally. Then in my example above it is too early for `#Ceil` to be introduced, because the rule for `#assume` doesn't unify with parts of configuration that contain `#buf`. So it appears to be a bug indeed.
3. From your explanation for #1911 it appears that `#Ceil(foo())` will work pretty much as I explained 2 posts above ("This means that we will generally evaluate a `#Ceil( #buf(...) )` the first time the `#buf(...)` appears"). Then situation discussed here remains a possibility.

**Comment by ttuegel** [comment]
> Then what's the point of creating #Not #Ceil(foo()) branch in the first place?

The `#Ceil` becomes part of the rule's `requires` clause. It's implicit in the way the rule is written. The `#Not #Ceil` comes from negating the `requires` to calculate the remainder of the original configuration after the rule is applied.

> the rule for #assume doesn't unify with parts of configuration that contain #buf.

Every rewrite rule unifies with the entire configuration at every step of the proof. Any part that is not explicitly mentioned in the rule is filled in with generated variables by the frontend. Therefore, the following statement is not correct:

> in my example above it is too early for #Ceil to be introduced

In fact, the `#Ceil` are introduced at every step from the time that `#buf` enters the configuration.

> Then situation discussed here remains a possibility.

I don't think so. In fact, you should be able to remove the `#Ceil(#buf)` rule from the semantics entirely without affecting the proof _if_ the range of `Int` variables is already established in the claim's `requires`. It should not be possible anymore for a `#Ceil` condition to cause a proof to get stuck. At least, not for any `#Ceil` term created by unification. I would need to see an example that isn't a backend bug in order to understand what we should display here.

**Comment by denis-bogdanas** [comment]
1. Regarding this concrete issue, this assumption is false:

> the range of `Int` variables is already established in the claim's `requires`

In this example range was established after creation of `#buf`. The range was not established in the initial proof rule (or claim, whatever), but in the `ensures` of a definition rule, which was executed after `#buf`. So I had to refactor the semantics to establish the range simultaneously with `#buf`. Similar situations may happen for other reasons: bugs in semantics or (very likely) missing lemma for `#Ceil` content.

2. It is clear now that understanding `#Ceil` logic is non-trivial and important for a kprove user. From your explanation many things are still not clear. So instead of bombarding you with questions, please take some time to write a wiki page about `#Ceil` purpose and implementation in the backend. ERC20 project is virtually finished, but for a new project, clearly understanding what the backend is doing is probably more important than fixing non-blocking workable-around bugs.

**Comment by ttuegel** [comment]
> The range was not established in the initial proof rule (or claim, whatever), but in the `ensures` of a definition rule, which was executed after `#buf`.

The range was actually set at the moment that `#buf` entered the configuration, but there was a bug in the backend where that was not recognized (#1665). Since the range of variables seems to only be set in order to satisfy the `#Ceil(#buf)` rule, I still think this rule could now be removed.

I added a page to [the wiki](https://github.com/kframework/kore/wiki/%23Ceil) based in part on our discussion, but I can't think of much to say about it that I haven't already. At one time, we thought it was going to be important for users to write `#Ceil` rules for their semantics, but that was really a workaround for a bug in the backend. I don't think it should be common to write `#Ceil` rules. The only reason I can think of to have them, is if the user wants the backend to infer something else (unrelated to `#Ceil`) from the presence of a term in the configuration.

**Comment by denis-bogdanas** [comment]
1. I don't understand what you are talking about. Please be more specific about what you are assuming, on what semantics/branch etc. You are probably talking about what happens in the corrected erc20-verification branch `symb-test-kevm-master` or some older branch you've seen last time. This issue discusses a situation that happened in an earlier commit. There range was not set the moment `#buf` entered the configuration.

2. Thanks for opening the wiki page. A few points are worth clarifying. 
(a) What is the purpose of `#Ceil` rules? I understand to specify when partial functions are defined. If a regular rule introduces a partial function, it can only apply when definedness conditions for that function are satisfied.
(b). I understand that `#Ceil` is introduced not only when `X` unifies with `foo`, but also when it unifies with a term containing `foo`. If this follows from some recursive evaluation of `#Ceil` then evaluation algorithm should be explained. It is not obvious. What happens when term is functional or is a constructor, of if it doesn't have `#Ceil` rules? Also please make it explicit when it happens: at every step of execution, in the process of rule matching.
(c) What happens if `foo` is created by equation `rule bar(X) => foo(X)` ? Is there still any variable unifying with `foo` here?
(d) I guess final implication happens at the end of a step, after the rule was applied.
(e)
> This case can often be refuted by applying the formula T = T #And #Ceil(T) to the configuration.
If `T` only exists as part of the `#Not #Ceil( T )`, this looks unsound. Please clarify the _often_ above.

**Comment by denis-bogdanas** [comment]
Just double-checked that the commit which produced discussed issue used Haskell backend with #1665 fix.

**Comment by ttuegel** [comment]
> Please be more specific about what you are assuming, on what semantics/branch etc. You are probably talking about what happens in the corrected erc20-verification branch `symb-test-kevm-master` or some older branch you've seen last time. This issue discusses a situation that happened in an earlier commit. There range was not set the moment `#buf` entered the configuration.

I am not making any assumptions about the semantics, or assumptions about any particular branch. I am only talking about Matching Logic. These are valid statements in Matching Logic:

```
(1)    φ = φ #And #Ceil( φ )  // φ is any pattern
(2)    #Ceil( σ(φ₁, φ₂, ...) ) #Implies #Ceil( φ₁ ) #And #Ceil( φ₂ ) #And ...  // σ is any symbol, φᵢ are any patterns
```

Let the left-hand side of the proof claim be `config #And side-condition` where `config` is just the "cells". Statement (1) above allows us to elaborate,

```
config #And side-condition = config #And #Ceil( config ) #And side-condition
```

This is strictly equality, we are just being explicit about the content of the claim. Statement (2) above allows us to elaborate further: For any term `tᵢ` appearing in any (sub-)cell of `config`, we can add `#Ceil( tᵢ )` to the left-hand side of the claim (because cells are symbols in Kore):

```
config #And #Ceil( config ) #And side-condition =
    config #And #Ceil( config ) #And #Ceil( t₁ ) #And #Ceil( t₂ ) #And ... #And side-condition
```

As a concrete example, whenever `#buf(...)` appears inside some cell in the configuration, its defined-ness condition `#Ceil( #buf(...) )` is _implicitly_ part of the left-hand side of the claim. That's what I mean by this:

> The range was actually set at the moment that #buf entered the configuration

The bug in #1665 is that the backend did not exploit this fact. The solution was to make these implicit conditions into explicit conditions.

I think this also clarifies your point here:

> If T only exists as part of the #Not #Ceil( T ), this looks unsound. Please clarify the often above.

`T` is the top-cell, but by statement (2) above it is also extended to the contents of any sub-cell.

**Comment by ttuegel** [comment]
The error here is actually a manifestation of #2021. The proof is not actually stuck, but due to a book-keeping error, the backend reports it as a stuck state. Actually, this state was proven as expected.
