### ISSUE TITLE
Unsimplified function in proof that used to work KEVM - merkle-spec

### ISSUE THREAD

**Issue by ehildenb** [kframework/kore#2076]
KEVM version:  860d6b92 from https://github.com/kframework/evm-semantics/pull/894
K version: 78b8132f1
Haskell Backend version: b2f05a75

Attached is a generated bug report. It ends in a term:

```
  #Ceil ( MerkleUpdate ( .MerkleTree , b"" , V ) )
#And                 
  #Not ( {                   
    MerkleUpdate ( .MerkleTree , b"" , V )
  #Equals            
    MerkleLeaf ( b"" , V )
  } )                 
#And                
  #Not ( {                  
    V                       
  #Equals      
    ""                      
  } )                       
#And           
  <kevm>           
    <k>                     
      doneMerkle ( MerkleUpdate ( .MerkleTree , b"" , V ) ) ~> .
    </k>         
    ...   
```

But we have the rule (in serialization.md):

```
    rule MerkleUpdate ( TREE, PATH:ByteArray, VALUE ) => MerklePut ( TREE, PATH, VALUE ) requires VALUE =/=String "" 
```

which I expect to apply (the side condition `VALUE =/=String ""` is on the original proof claim).

Bug report attached: 
[kevm-bug.tar.gz](https://github.com/kframework/kore/files/5086009/kevm-bug.tar.gz)

**Comment by ttuegel** [comment]
After #2014, the backend simplifies `V =/=String ""` to `\not(\equals(V, ""))` which exposes more terms to its internal unification algorithms (good) but prevents sending the term directly to the solver, which does not have a builtin String sort. This is not inherently a problem; the backend can translate `\equals(V, "")` to a Bool-valued SMT variable and this suffices as long as it is translated to the same variable everywhere. Unfortunately, it isn't being translated to the same variable everywhere because `\equals` carries extraneous sort information. This would be fixed by solving #1442, but a more immediate solution is to erase the sort information of predicates before sending them to the solver.
