### ISSUE TITLE
Modify Syntax of Kore

### ISSUE THREAD

**Issue by msaxena2** [kframework/kore#21]
@grosu

**Comment by grosu** [comment]
Done.  Please check the KORE language syntax page: https://github.com/kframework/kore/wiki/KORE-Language-Syntax.  Just found that I used `p` and `q` instead of `_1` and `_2`.

@msaxena2, please check that I used the right Scala code and add a link to the code once you merge the pull request.

@cos, it would be nice to add some examples with `List{X}` and `Set{X}`.

**Comment by grosu** [comment]
Haven't heard from anybody, so closing this issue.
