### ISSUE TITLE
MultiOr's \bottom and MultiAnd's \top should not lose information

### ISSUE THREAD

**Issue by ana-pantilie** [kframework/kore#2158]
When the inner type is `Pattern`, for example, the sort information gets lost.

**Comment by ttuegel** [comment]
I think the best way to handle this is to change the behavior so that when a `MultiAnd` or `MultiOr` is `\top` or `\bottom` respectively, we keep the `\top` or `\bottom` element; but only if it is the singular element of the (con,dis)-junction.

I also thought about adding a `Sort` field, but then the types wouldn't be usable with things that don't have a canonical sort, and I don't like that.

**Comment by ttuegel** [comment]
After #1442, most of the uses of the phony `_PREDICATE` sort will go away anyway, so we decided to wait until the relevant pull request is merged and deal with the remaining uses by removing `mkTop_` and `mkBottom_`. We will have to keep track of some sorts directly in the code (rather than tracking them in the `MultiAnd` data structure), but we will need to keep track of the sort there anyway.
