### ISSUE TITLE
`--strategy all` is ignored

### ISSUE THREAD

**Issue by nishantjr** [kframework/kore#2205]
This happens for both non-deterministic semantics, and when multiple branches are available for narrowing.
We expect both the following tests to result in a disjunction of configurations (two for the first, three for the second).

```
$ cat test.k
module TEST
    imports INT
    configuration <k> init </k>
    syntax KItem ::= "init"
    rule <k> init => 1 </k>
    rule <k> init => 2 </k>
endmodule

$ kompile test.k --backend haskell
$ krun --haskell-backend-command 'kore-exec --strategy all'
<k>
  2 ~> .
</k>
```

```
$ cat test.k 
module TEST
    imports INT
    configuration <k> init </k>
    syntax KItem ::= "init" | "one" | "two"
    rule <k> init => ?_:Int </k>
    rule <k> 1 => one </k>
    rule <k> 2 => two </k>
endmodule
$ KORE_EXEC_OPTS="--strategy all" krun
  <k>
    two ~> .
  </k>
#And
  {
    'QuesUnds'0
  #Equals
    2
  }
```

**Comment by ttuegel** [comment]
- [This](https://github.com/kframework/kore/blob/11e10fbb61a31ef555f15d44721dc6253ab787e7/kore/src/Kore/Exec.hs#L284) should change to `OrPattern` (the configurations)
- [Apply](https://github.com/kframework/kore/blob/11e10fbb61a31ef555f15d44721dc6253ab787e7/kore/src/Kore/Exec.hs#L291) the `getExitCode` symbol to each configuration.
- Call `MultiOr.gather` [here](https://github.com/kframework/kore/blob/11e10fbb61a31ef555f15d44721dc6253ab787e7/kore/src/Kore/Exec.hs#L290).
- In the [case](https://github.com/kframework/kore/blob/11e10fbb61a31ef555f15d44721dc6253ab787e7/kore/src/Kore/Exec.hs#L293), we should return the exit code if all the branches agree about the exit code, otherwise we [return](https://github.com/kframework/kore/blob/11e10fbb61a31ef555f15d44721dc6253ab787e7/kore/src/Kore/Exec.hs#L297) `111`
