### ISSUE TITLE
Dereference `unit` and `element` symbol attributes

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2222]
We should use the `unit` and `element` symbol attributes so that we don't need `MetadataTools` in `Kore.Builtin.internalize`. The `MetadataTools` are used to construct the internal representations of builtin Map, Set, and List sorts; we need to look up the `unit` and `element` symbols of the sort's `concat` symbol. If this was in the symbol attributes already, there would be no need no look it up.

Needs kframework/k#1614

**Comment by MirceaS** [comment]
It turns out that using the proposed workaround for no longer needing `MetadataTools` for internalization has the potential to produce un-unparsable `InternalAc`'s that we should be able to unparse. This can happen after, for instance, removing an entry from a singleton `InternalMap`(say `1 |-> 1`) that doesn't know it's unit symbol but gets turned into the empty map via a builtin function.
This led us to decide to no longer fix this issue. As a result of that, we will revert the PR that attempted to fix the issue and any PR that depended on this PR.
