### ISSUE TITLE
Cache the results of applying equations at the level of individual equations

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#2321]
This would improve performance significantly. The advantage of caching the result of applying individual equations is that it would allow us to skip equations which do not match. Otherwise, we would get cache hits only when a term is simplifiable. A significant performance problem for us is large symbolic terms which are not simplifiable because we must try to re-simplify them frequently.

**Comment by ttuegel** [comment]
Actually, it might be better to do this at the level of function evaluators. We could, for example, skip directly to equations we know could match the term. This should wait until after #2470 and #1978.

**Comment by ana-pantilie** [comment]
Will this issue still be valid after https://github.com/kframework/kore/issues/2520?

**Comment by ana-pantilie** [comment]
@ttuegel suggests we profile `specs/benchmarks/encode-keccak00-spec.k` and `specs/benchmarks/storagevar03-spec.k`, see if we spend too much time trying to apply equations.

**Comment by ana-pantilie** [comment]
I want to be 100% sure I understand what this issue is about. My current understanding is the following:
- the first time equation `E` gets attempted on term `T`, and it doesn't apply:
    - if it doesn't apply because it doesn't match, we store that term in `E`'s evaluator;
    - if it doesn't apply because of the side condition, we store the term and its side condition;
- the second time `E` is attempted on `T`, we'll look at the stored information; if the current side condition has changed, we attempt to apply it again;

Is this the right interpretation? Or have I completely missed the point? :smile:

**Comment by ana-pantilie** [comment]
Also, should this still wait until https://github.com/kframework/kore/issues/1978?

**Comment by ttuegel** [comment]
> Is this the right interpretation? Or have I completely missed the point?

Yes, this is exactly right.
