### ISSUE TITLE
Bool expression constrained to false not evaluated

### ISSUE THREAD

**Issue by denis-bogdanas** [kframework/kore#2358]
erc20 verifier is stuck with:
```
#And
  #Ceil ( #buf ( 32 , ?ACCT ) )
#And
  #Not ( {
    true
  #Equals
    #lookup ( ?STORAGE , keccak ( #buf ( 32 , ?ACCT ) ++ b"0000000000000000000000000000000000000000000000000000000000000000" ) ) <Int ?SYMB_INT
  } )
...
      <k>
        JUMPI 1242 bool2Word ( #lookup ( ?STORAGE , keccak ( #buf ( 32 , ?ACCT ) ++ b"0000000000000000000000000000000000000000000000000000000000000000" ) ) <Int ?SYMB_INT ) ~> ...
      </k>
```

`#lookup` expression inside `bool2Word` should evaluate to false.

https://office.runtimeverification.com/jenkins/blue/organizations/jenkins/erc20-verification/detail/PR-151/22/pipeline

Can you propose a workaround until this is fixed?

**Comment by ttuegel** [comment]
> `#lookup` expression inside `bool2Word` should evaluate to false.

Can you explain how we can know that? It isn't obvious to me.

**Comment by denis-bogdanas** [comment]
From the side condition above. The expression inside `bool2Word` is the same.

**Comment by ttuegel** [comment]
By means of a counter-example: if the sub-term `#lookup ( ?STORAGE , ... ) #Equals #Bottom`, then the whole term is `#Bottom`, not `false`. This is possible because `#buf` is partial.

**Comment by denis-bogdanas** [comment]
There is also this side condition:
```
#And
  #Ceil ( #buf ( 32 , ?ACCT ) )
```
Edited fragment above to include it. All other functions in `#lookup` term are functional.

**Comment by denis-bogdanas** [comment]
What's your opinion after above update?

**Comment by ttuegel** [comment]
The backend is not yet clever enough to extract the relevant `#Ceil` fact from the side condition, but there is work in this direction (#2351).

In any case, I recommend modifying the partial `#buf` abstraction in `edsl.md` to be total by separating the cases where it is defined and undefined. For example,

``` k
    syntax ByteArray ::= #bufExtended ( Int , Int ) [functional, smtlib(buf)]
    // Extends the domain of the original #buf by interpreting DATA modulo 2 ^Int (SIZE *Int 8).
    rule #bufExtended(SIZE, DATA) => #padToWidth(SIZE, #asByteStack(DATA %Int (2 ^Int (SIZE *Int 8))))
      [concrete]

    syntax ByteArray ::= #buf ( Int, Int ) [function]
    rule #buf(SIZE, DATA) => #bufExtended(SIZE, DATA)
      requires #range(0 <= DATA < (2 ^Int (SIZE *Int 8)))
    rule #buf(_, _) => #Bottom
      [owise]

    // The lemmas about #buf must also be changed to use #bufExtended.
```

There are other ways we could divide up the behavior, but the point is to separate early the cases when `#buf` is and is not defined so that we can reason separately about the case where it is defined. We will continue working to make the backend more clever, but I think separating defined and undefined cases like this will always make reasoning easier.

**Comment by denis-bogdanas** [comment]
That's a great suggestion, thanks! I guess this will also eliminate all `#Ceil` terms from side condition and make evaluation faster. Right now all `#Ceil` terms are caused by `#buf`.
