### ISSUE TITLE
kprove: Crashes when a rule using #Bottom occurs

### ISSUE THREAD

**Issue by nishantjr** [kframework/kore#2561]
K Version
---------

```
K version:    5.0.0
Build date:   Mon Apr 19 04:38:10 CDT 2021
```

Description
-----------

kprove crashes with message "cannot assume a \bottom pattern is defined"

Reproduction & input files
-----

```
$ cat test.k
module TEST
    configuration <k> foo </k>
    syntax KItem ::= "foo"
    rule foo => #Bottom 
endmodule

$ kompile --backend haskell test.k

$ cat test-spec.k
module TEST-SPEC
    imports TEST
    imports INT-SYNTAX
    claim <k> foo => 1234 </k> 
endmodule

$ kprove test-spec.k
kore-exec: [142996] Error (ErrorException):
    Internal error: cannot assume a \bottom pattern is defined.
    CallStack (from HasCallStack):
      error, called at src/Kore/Internal/SideCondition.hs:662:17 in kore-0.43.0.0-HgLSPgFtvBzHoiXRxMegel:Kore.Internal.SideCondition
Created bug report: kore-exec.tar.gz
[Error] Internal: Uncaught exception thrown of type NoSuchElementException.
Please rerun your program with the --debug flag to generate a stack trace, and
file a bug report at https://github.com/kframework/k/issues
(NoSuchElementException: key not found: append)
```

Expected Behavior
-----------------

`kprove` should return `#Top`.

**Comment by ttuegel** [comment]
- Refactor [`simplifyTopConfiguration`](https://github.com/kframework/kore/blob/e0614507f2172e8d161fa8e8eddd844dba724eae/kore/src/Kore/Step/Simplification/Pattern.hs#L70) so that it takes the `TermLike` from the `Pattern` as the defined term.
- Return `Maybe` from [`assumeDefined`](https://github.com/kframework/kore/blob/39a42a5a7d2245086d31fa2a0b5fa1a84e40f456/kore/src/Kore/Internal/SideCondition.hs#L613) to ensure that we have correct handling of `\bottom` everywhere.
