### ISSUE TITLE
Why so many whitelines?

### ISSUE THREAD

**Issue by grosu** [kframework/kore#27]
Is there a specific Scala style where they recommend whitelines between `def` members, like in the code below?
```
trait SortedVariable extends Variable {
  def name: Name

  def sort: Sort
}
```
If not, I would suggest that we get rid of these whitelines, so the code looks more compact and easier to read.

**Comment by cos** [comment]
There's no standardized convention, afaik. I don't quite like them either, but it's the default style in IntelliJ. We can decide to change it but then we'll have to make sure people contributing code will use the updated format, i.e., configure IntelliJ to load our format file.

**Comment by grosu** [comment]
If it is the default IntelliJ style for Scala, then I think we should keep it as is.  But what happens if we remove the whiteline by hand?  Do we get any IntelliJ formatting error or warning?

**Comment by cos** [comment]
There would be no warnings for formatting. It's just that if anyone automatically reformats the entire file (via a shortcut) it will move many things around. In general, it can be a good idea to keep things automatically formatted so that we have minimal merge issues related to formatting only.

**Comment by msaxena2** [comment]
I tend to use intellijs autoformatting quite a bit. If we want to remove
the whitespace, I'd prefer to just put the intellij's settings file under
version control.

On 30 May 2017 12:29 pm, "Cosmin Radoi" <notifications@github.com> wrote:

There would be no warnings for formatting. It's just that if anyone
automatically reformats the entire file (via a shortcut) it will move many
things around. In general, it can be a good idea to keep things
automatically formatted so that we have minimal merge issues related to
formatting only.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/kframework/kore/issues/27#issuecomment-304950397>, or mute
the thread

**Comment by grosu** [comment]
I think it is easier to just leave it as is.  People may use other editors, too.  So I'm closing this.
