### ISSUE TITLE
Regression: Kprove hangs instead of crashing

### ISSUE THREAD

**Issue by SchmErik** [kframework/kore#2878]
Test file:
------------
```
module TEST
    imports MAP
    imports BOOL

    syntax Foo ::= "a" | "b" | "c"
 // ------------------------------
    rule <k> a => b ... </k>

endmodule

module TEST-SPEC
    imports TEST

    claim <k> (a ~> _ => .) ... </k>
 
endmodule
```

Commit https://github.com/kframework/kore/commit/ed422630f9383b2774f1ec8ea04eee86ea0afe1e changed the behavior of running kprove on this test case.
In order to reproduce this behavior I create a makefile with the following lines and run `make`:
```
all:
	rm -rf *-kompiled .kprove*
	kompile --main-module TEST --backend haskell test.k
	kprovex test.k --spec-module TEST-SPEC --debug 
```
Prior to this commit, the kfrontend code crashed on a pattern match error shown in https://github.com/kframework/k/issues/2245 and I'm expecting this crash to continue to happen. The actual behavior seems to hang sometime before kore is printed. I also found that adding `--depth 0` to the last command causes the pattern match crash to happen.

**Comment by SchmErik** [comment]
I added this test case to the k repo with the `--depth 0` option to get it to complete. Once this regression is resolved in the haskell backend, we should remove this option from the test. I made this change in this pull request here: https://github.com/kframework/k/pull/2279 Once this is resolved, let's merge this PR so that we can create a regression test for this.

**Comment by ana-pantilie** [comment]
I'm going to record my progress on the issue here in order to provide a clear report of my progress but also to document the debugging process for other members of the Haskell backend team.

1. I managed to reproduce both the looping behavior and the `--depth 0` behavior on the current kore master.
2. I ran `kprovex` with `--debugger` to start the `kore-repl`. I observed that taking one single step (with the `step`) command induces the looping behavior.
3. I restarted the `kore-repl` and I switched on the logging for `DebugAttemptEquation` entries with `log [DebugAttemptEquation] stderr`. This is to make sure that it isn't looping when applying equations. When stepping, I noticed that after a few log entries it stopped printing anything, suggesting that it's looping in some specific point in the simplifier.
4. I restarted the `kore-repl` and I switched on the logging for all log entries: `log debug [] stderr`. I noticed that it kept printing the following log entries:
```
kore-repl: [188419768] Debug (DebugSubstitutionSimplifier):
    (InfoReachability) while checking the implication:
    (DebugSubstitutionSimplifier) while simplifying substitution:
    Non-\bottom result
kore-repl: [188422090] Debug (DebugSubstitutionSimplifier):
    (InfoReachability) while checking the implication:
    Simplifying substitution
```
This suggests that it's looping in the substitution simplifier, inside the `CheckImplication` transition. I believe I should continue by adding traces in that part of the code, to figure out which substitution that is.
The relationship between the commit where the regression appeared and this behavior is still unclear to me.
