### ISSUE TITLE
The initial structure of the K files is broken during the translation with "kompile"

### ISSUE THREAD

**Issue by amelieled** [kframework/kore#2972]
There are two main questions here:
 1. Is it possible to find the initial structure of the K files, using the attributes present in Kore?
 2. Do you plan to keep the initial structure of the K files into the generated Kore files, in the future?

**Comment by ana-pantilie** [comment]
Hi @amelieled. These questions are more suited for the K repository, since that's where the translation from K to Kore and back happens. I'm going to close this, and I suggest it's best if you ask in the `k-public` Slack channel if you have access to it. If you don't, then ask the questions in https://github.com/runtimeverification/k. Thank you.

**Comment by amelieled** [comment]
Hi @ana-pantilie .
OK, I see, thanks! The code of the translation from K to Kore isn't here.
Where is the link to the Slack channel?

**Comment by ana-pantilie** [comment]
@amelieled There's a riot room bridged to it, so you can chat and ask questions from: https://riot.im/app/#/room/#k:matrix.org
