### ISSUE TITLE
Partial function evaluation

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#665]
Sometimes the backend gets stuck when a function's definition is partial, even if the ambient constraints would restrict to the cases where the function is defined.

There is an example on [my branch](https://github.com/ttuegel/kore/tree/example-partial-function/src/main/k/working/functions):

`functions.k`:
```
module FUNCTIONS

  imports HARNESS
  imports BOOL
  imports INT

  rule <k> begin => next true </k>

  // `positive` is defined if its argument is positive.
  syntax Bool ::= positive(Int) [function]
  rule positive(M) => true
    requires M >Int 0

endmodule
```

`positive-spec.k`:
```
module POSITIVE-SPEC

  imports FUNCTIONS

  // test claim
  rule
    <k> begin => end </k>
    <n> N </n>
    requires N >Int 0

  // applies only if `positive` is defined
  rule
    <k> next positive(N) => end </k>
    <n> N </n>
    [trusted]

endmodule
```

The function `positive` is only partially defined, but it occurs only under constraints which ensure it is defined. The proof still gets stuck on this remainder:
```
  #Not ( #Ceil ( positive ( N ) )
  #And
    {
      positive ( N )
    #Equals
      true
    } )
#And
  <T>
    <k>
      next true
    </k>
    <n>
      N
    </n>
  </T>
#And
  {
    N >Int 0
  #Equals
    true
  }
```

The constraint `N >Int 0 #Equals true` ensures that `#Ceil ( positive ( N ) )` and `positive ( N ) #Equals true`. We cannot see that until we apply the definition of `positive`, but we won't apply the definition until we see that.

Something similar occurs if the function occurs in a `requires` clause instead:

`positive-requires-spec.k`:
```
module POSITIVE-REQUIRES-SPEC

  imports FUNCTIONS

  // test claim
  rule
    <k> begin => end </k>
    <n> N </n>
    requires N >Int 0

  // applies only if `positive` is defined
  rule
    <k> next _ => end </k>
    <n> N </n>
    requires positive(N)
    [trusted]

endmodule
```

The stuck configuration is:
```
  #Not ( {
    positive ( N )
  #Equals
    true
  } )
#And
  <T>
    <k>
      next true
    </k>
    <n>
      N
    </n>
  </T>
#And
  {
    N >Int 0
  #Equals
    true
  }
```

**EDIT**: Simplify the example and add the `requires` example.

**Comment by ttuegel** [comment]
The reason we do not eagerly expand `partially` is that—absent proof that its definition is complete in context—it tends to blow up.

**Comment by ttuegel** [comment]
Re-enabling function remainders solves this problem and improves performance by attempting each function evaluation only once. However, disabling function remainders also allows recursive functions like this one to work:
```
  syntax ConsList ::= ".ConsList" | KItem ":" ConsList
  // `length` is recursively defined.
  syntax Int ::= length(ConsList) [function, functional]
  rule length(.ConsList) => 0
  rule length(_ : TAIL) => 1 +Int length(TAIL)
```
Now (on my branch) this function loops indefinitely with symbolic input, e.g. in this spec,
`length-spec.k`:
```
module LENGTH-SPEC

  imports FUNCTIONS

  // test claim
  rule
    <k> begin => end </k>
    <n> LIST:ConsList </n>
    requires length(LIST) >Int 1

  // applies only if initial condition applied
  rule
    <k> next _ => end </k>
    <n> LIST:ConsList </n>
    requires length(LIST) >Int 1
    [trusted]

endmodule
```
I think we need to disable eager function evaluation entirely and evaluate functions only as required by unification (lazily). @virgil-serbanuta What do you think? We have bounced this idea around before.

**Comment by virgil-serbanuta** [comment]
That's reasonable, but we must be a bit careful, expanded functions may also be useful to, say, the SMT solver. It might be a good idea to generalize this to "evaluate when needed" (though that might be somewhat harder to implement than ). By-need evaluation might or might not include printing the output at the end of the program (which makes sense for normal execution, maybe also for symbolic execution).

Also, while this makes sense for symbolic execution/proving, I'm not yet confident it's a good idea for normal execution (though it might be, since lazy evaluation seems to work for various programming languages).

Also see:
https://github.com/kframework/kore/blob/master/docs/2018-12-21-Function-Evaluation.md

As an alternate option, separating patterns in "already evaluated" and "changed since the last evaluation" as described below, could solve the partial function issues:

https://docs.google.com/document/d/18fWqzbZEWP9Rk2Cs8WAmLo_xASHs5snATC2Rqc6bXoI/edit?usp=sharing

**Comment by ttuegel** [comment]
You're right, "when needed" is more complicated than just "during unification". I think I would like to work around that for now by adopting a simpler solution for this problem, which I will describe below.

Aside: I've been working on a blog post about lazy evaluation in Haskell, where "when needed" is exactly "during unification (pattern matching)", so I was only thinking about the pattern-matching case.

To solve this, I propose to add a symbol attribute `inductive(n)` to indicate than a symbol is defined inductively on the `n`-th argument. We would not evaluate any occurrence of the symbol which does not have a constructor at the top of its `n`-th argument. The user will know best when to add this attribute, but eventually we can infer it if necessary.

**Comment by virgil-serbanuta** [comment]
In Haskell, doesn't "when needed" include printing, or is that also done through pattern matching? To be precise, printing a string may involve pattern matching, but it does not seem obvious that transforming an int to a string for printing involves pattern matching.

**Comment by ttuegel** [comment]
When you do something like `putStr a` where `a = show (5 :: Integer)`, `putStr` is doing something like, `case a of { x : xs -> putChar x >> print xs; [] -> return ()}`. The runtime system enters the thunk of `a` and executes until it gets to the first constructor in the string (list). `putStr` is probably not a great example because there is going to be some extra interaction with foreign code (to talk to the operating system), but operationally there is nothing more complex than pattern matching happening.

**Comment by ttuegel** [comment]
Following a suggestion by @ehildenb, I also tried modifying function evaluation so that it will not narrow function patterns. This also effectively prevents the infinite recursion. It also breaks a few unit tests that were using narrowing on function definitions to test having multiple function results. If function symbols are supposed to be single-valued, I don't know if we should be returning multiple results anyway. Nevertheless, I should be able to fix the unit tests.

@traiansf @virgil-serbanuta Do we have a preference for a solution here? Either disable narrowing during function evaluation or using an `inductive` attribute? If we go with the former, we can use matching instead of unification for function rules, which could be much faster. But the latter is more targeted to this specific problem, and gives the user a little more control.

**Comment by virgil-serbanuta** [comment]
1. I don't care about functions returning multiple results, but I do care about function evaluation splitting a single result into multiple branches.

2. "we can use matching instead of unification for function rules, which could be much faster" - I keep hearing this and I keep explaining why it's likely not true for our backend (except, perhaps, as some missed optimization case that could be quickly fixed; I expect unification to take slightly more than matching on all practical cases, but not much more). While I may have not explained it in a place visible to you, explaining it does not seem to work in general, so I'm not going to try again. Since, as far as I know, nobody tried to actually measure this for our code, could we add a task about looking into this problem (perhaps both for the measurement and for the missed optimizations)? That would allow us to make informed decisions and would prevent us from wasting time discussing things which can't really be decided through discussions.

3. Using matching instead of unification seems to mostly work, but I don't understand it well enough to say that it always works, and, being a non-trivial problem (at least for me), my default assumption would be that it does not always work unless someone shows me otherwise. Also, my default assumption is that we do want to have narrowing sometimes (I also vaguely remember some tests which had functions that didn't work with the SMT, but which could be evaluated through narrowing, it may have been an "if" function or something similar), so we may not be able to get rid of unification anyway.

Given all of the above, I'd do one of the following (in order of preference):

a. Use unification with something that prevents infinite recursion (with an `inductive` attribute if you prefer that).
b. Use matching in a way in which we can easily switch back to unification, crashing the backend whenever we have a function remainder (we might need to take into account the top-level predicates in order to safely discard some of these remainders).
c. Produce a design document (or a Slack post if that's enough) with a detailed enough explanation of why matching instead of unification would work, identifying the assumptions needed for that (if any) and what would happen with function evaluation when the matching and the unification output would be different (includes narrowing not working, but it should include an explanation on why using a matching unifier instead of the most general one is good enough, or perhaps an explanation of why the matching unifier is the most general one). Then we could add assertions for all the assumptions above (if any), fallback cases (if needed) and then we would safely use matching.
d. Someone that understands unification and matching well enough says that using matching is safe, and that my requests in c. are not necessary, and we implement matching.

**Comment by ttuegel** [comment]
Following our discussion in this morning's stand-up meeting, I am going to proceed with option (a) above, "unification without narrowing" for function evaluation.
