### ISSUE TITLE
Use top-level constraints when applying function rules

### ISSUE THREAD

**Issue by ttuegel** [kframework/kore#734]
Following a discussion with @yzhang90, @traiansf, and @virgil-serbanuta, we decided that it is safe to try evaluating function rules in the presence of the top-level constraints. Furthermore, if we check that the top-level constraints imply the conditions on the rule, then we do not have to modify the constraints when we apply the rule (see #705). @yzhang90 also suggested that we can try to split the configuration at the top-level when applying functions, although this may not work under binders.

**Comment by ttuegel** [comment]
I discussed this with @yzhang90 again yesterday. We realized there are two possible approaches:

1. Function evaluation can happen at any time during simplification, so carry the top-level constraints with us as we travel down the pattern. (Until now, we have focused exclusively on this option.)
1. Separate function evaluation from other simplifications, i.e. evaluate functions during a separate pass when we have the top-level constraints available.

**Comment by virgil-serbanuta** [comment]
Option 2 above is a bit confusing for me.

Function evaluation is, in part, defined with axioms, and, in part, defined in Haskell (the builtin stuff).
 
Ceil is also a mix of axiom-based simplifcation and Haskell code, and I think that, for most pattern types, we could define simplification through axioms if we wanted to (I guess it would make it much easier to generate proofs).

So, is option 2 about:
a) The axiom part of function definition
b) All of function definition
c) Any simplification that is axiom-based
d) Something else
?

My initial guess was that it was about (c) or (c+b), but then I wasn't fully sure that we could separate (c) cleanly from the other Haskell code. Most likely we can, but I didn't think through all the corner cases.

Anyway, I'm in favor of option 1 because otherwise fully simplifying a term would mean doing simplification without application/axioms, followed by simplification with application/axioms, followed by simplification without application/axioms, followed by ... until the term stabilizes, and that doesn't seem very appealing (though I can be convinced otherwise).

**Comment by ttuegel** [comment]
> Anyway, I'm in favor of option 1 because otherwise fully simplifying a term would mean doing simplification without application/axioms, followed by simplification with application/axioms, followed by simplification without application/axioms, followed by ... until the term stabilizes, and that doesn't seem very appealing (though I can be convinced otherwise).

That's a good point, and I agree.
