### ISSUE TITLE
Conditional datatype doesn't unparse to correct Kore

### ISSUE THREAD

**Issue by ana-pantilie** [kframework/kore#767]
`Kore.Internal.Conditional`: unparse instance ignores sorts by replacing them with `_` or `_PREDICATE`

**Comment by ttuegel** [comment]
The `Unparse` instance for `Conditional` should be removed; we can only unparse a `Kore.Internal.Pattern.Pattern`, not an arbitrary `Conditional`. The `Predicate` should be assigned the same sort as the `TermLike`, otherwise the frontend will not be happy. Anything sent to the frontend needs to be run through [`Kore.Internal.TermLike.externalizeFreshVariables`](https://github.com/kframework/kore/blob/master/kore/src/Kore/Internal/TermLike.hs#L896), so it might be best to call that function as part of the `Unparse` instance.
