### ISSUE TITLE
Fix Kevm tests broken by function matching instead of unification

### ISSUE THREAD

**Issue by virgil-serbanuta** [kframework/kore#832]
See https://office.runtimeverification.com/jenkins/job/haskell-backend/job/master/219/

**Comment by virgil-serbanuta** [comment]
Most likely this fails because of #810 or #789, both of which timed out in out build system.

**Comment by virgil-serbanuta** [comment]
https://github.com/kframework/kore/pull/834 contains a test for this issue. Basically, we are trying to match `f(A|->B M, A)` against `f(1|->1 2|->2, 2)` and we are matching `A|->B` with `1|->1` and `A` with `2` which fails for the obvious reason.

We have two possible fixes:
1. Change matching to work in multiple steps (i.e. allow postponing matches). This can still fail, but it should work for most (all?) practical cases.
2. Revert to using unification.

What won't work:
1.

**Comment by ttuegel** [comment]
I am also inclined toward (1). We tried to get unification (2) working for function evaluation for a long time. It's not evident to me that we know how to make progress with (2). On the other hand, it seems like we have a good idea what is needed to make matching (1) work, so that seems less risky.

As far as grading the difficulty of matching candidates, I don't think we need to do anything fancy. If we only care about returning a single result from matching—which is what we want for function and simplification rules, at least—then I think we can grade every match candidate this way:

- zero solutions: match fails
- one solution: match succeeds, add the substitution to the solution
- unknown number of solutions: defer this candidate

This misses a few matching solutions, such as when two candidates each have several possible solutions, but they only agree on one solution. However, I don't think we need to worry about that because I don't think anyone expects to be able to write rules like that.

**Comment by ttuegel** [comment]
Fixed by: #835
