### ISSUE TITLE
Concrete definition rules prevent applying non-concrete rules

### ISSUE THREAD

**Issue by yzhang90** [kframework/kore#994]
In evm-semantics, there is a rule about `chop`,
```
rule chop ( I:Int ) => I modInt pow256 [concrete, smt-lemma]
```
The rule is marked as concrete in the semantics.
During proof, I tried to add a lemma about `chop` (for simplicity reason, i remove the conditions)
```
rule chop (I) => I
```
However, the lemma is not applied. 
Then I tried the following combination:
remove concrete rules+ add lemma: lemma is applied
keep concrete rule + add simplification att to lemma: lemma is applied

**Comment by virgil-serbanuta** [comment]
If it's not a simplification rule, then it's a function definition rule. If some of the function definition rules are concrete, it may be reasonable to not attempt to evaluate the non-concrete ones "just in case", especially since we expect to have no reminder after applying all definition rules.

In other words, we rely on function definition rules being separate from all the others (which we call "simplification rules"). So either we should be able to identify this rule as a non-definition one, or you should help the k-> kore kompiler with that information, otherwise things will not work as expected.

**Comment by yzhang90** [comment]
ok. i agree. I will wait for #973 to be implemented.
